Repository TobiasPrt/mate-app, pull requests merged in 2020-08, with the labels that each got.

#27 Revive
  .github/workflows/main.yml
  lib/main.dart
  lib/models/custom_query.dart
  lib/models/dish.dart
  lib/models/event.dart
  lib/models/home.dart
  lib/models/models.dart
  lib/models/news.dart
  lib/models/subject.dart
  lib/models/university.dart
  lib/models/user.dart
  lib/models/usermodel.dart
  lib/services/auth.dart
  lib/services/database.dart
  lib/services/globals.dart
  lib/services/services.dart
  lib/styles/styles.dart
  lib/utils/utils.dart
  lib/views/app.dart
  lib/views/main/einstellungen.dart
  lib/views/main/einstellungen_account.dart
  lib/views/main/einstellungen_datenschutz.dart
  lib/views/main/einstellungen_impressum.dart
  lib/views/main/einstellungen_version.dart
  lib/views/main/home.dart
  lib/views/main/home_veranstaltung.dart
  lib/views/main/mensa.dart
  lib/views/main/mensa_tab.dart
  lib/views/main/news.dart
  lib/views/main/news_detail.dart
  lib/views/main/verwaltung.dart
  lib/views/main/verwaltung_module.dart
  lib/views/main/verwaltung_module_tab.dart
  lib/views/main/verwaltung_noten.dart
  lib/views/main/verwaltung_personen.dart
  lib/views/main/verwaltung_pruefungsordnung.dart
  lib/views/setup/auth_switch.dart
  lib/views/setup/legal.dart
  lib/views/setup/semester.dart
  lib/views/setup/sign_in.dart
  lib/views/setup/sign_up.dart
  lib/views/setup/subjects.dart
  lib/views/setup/universities.dart
  lib/views/setup/welcome.dart
  lib/views/views.dart
  lib/views/wrapper.dart
  lib/widgets/loading.dart
  lib/widgets/mate_page_route.dart
  lib/widgets/sliver_loading_indicator.dart
  lib/widgets/tag.dart
  lib/widgets/widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#29 Mensa
  ios/Flutter/.last_build_id
  ios/Podfile.lock
  lib/services/auth.dart
  lib/services/database.dart
  lib/views/main/mensa.dart
Labels: bug, enhancement

#30 News
  ios/Podfile.lock
  lib/main.dart
  lib/services/auth.dart
  lib/services/database.dart
  lib/styles/styles.dart
  lib/utils/utils.dart
  lib/views/app.dart
  lib/views/main/mensa.dart
  lib/views/main/news.dart
  lib/views/main/news_detail.dart
  lib/views/main/verwaltung_module.dart
  lib/widgets/static_navigation_bar.dart
  lib/widgets/tag.dart
  lib/widgets/widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#31 get changes
  ios/Podfile.lock
  lib/main.dart
  lib/services/auth.dart
  lib/services/database.dart
  lib/styles/styles.dart
  lib/utils/utils.dart
  lib/views/app.dart
  lib/views/main/mensa.dart
  lib/views/main/news.dart
  lib/views/main/news_detail.dart
  lib/views/main/verwaltung_module.dart
  lib/widgets/static_navigation_bar.dart
  lib/widgets/tag.dart
  lib/widgets/widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#37 the version Page
  lib/views/main/einstellungen_version.dart
Labels: enhancement

#36 Code of Conduct Seite
  lib/views/main/einstellungen_code_of_cunduct.dart
Labels: enhancement

#35 Site notes
  lib/views/main/einstellungen_impressum.dart
  lib/widgets/static_navigation_bar.dart
Labels: enhancement

#33 Privacy
  lib/views/main/einstellungen_datenschutz.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#41 Home detail
  lib/styles/styles.dart
  lib/views/main/home.dart
  lib/views/main/home_veranstaltung.dart
Labels: enhancement

#39 Settings
  lib/views/main/einstellungen.dart
  lib/widgets/settings_list_item.dart
  lib/widgets/widgets.dart
Labels: enhancement

#42 Account with data
  ios/GoogleService-Info.plist
  lib/views/main/einstellungen_account.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#40 Account with pie chert implement
  lib/views/main/einstellungen_account.dart
Labels: enhancement

#43 Grades
  lib/styles/styles.dart
  lib/views/main/verwaltung_noten.dart
  lib/widgets/settings_list_item.dart
Labels: enhancement

#46 Verwaltung
  ios/Flutter/.last_build_id
  lib/models/subject.dart
  lib/models/university.dart
  lib/models/usermodel.dart
  lib/services/database.dart
  lib/views/main/einstellungen_code_of_cunduct.dart
  lib/views/main/einstellungen_datenschutz.dart
  lib/views/main/verwaltung.dart
  lib/views/setup/legal.dart
  lib/views/setup/semester.dart
  lib/views/setup/subjects.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#45 implmented grade scraping trigger
  ios/Podfile.lock
  lib/main.dart
  lib/models/grade.dart
  lib/services/auth.dart
  lib/views/main/einstellungen.dart
  lib/views/main/einstellungen_account.dart
  lib/views/main/verwaltung.dart
  lib/views/main/verwaltung_noten.dart
  lib/widgets/static_navigation_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement
